### ISSUE TITLE
安卓13闪退

### ISSUE THREAD

**Issue by Simlalsy** [xiaofei-dev/Vibrator#4]
MIUI14 安卓13 闪退

**Comment by Simlalsy** [comment]
> MIUI14 安卓13 闪退

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.xiaofei_dev.vibrator/com.github.xiaofei_dev.vibrator.ui.MainActivity}: java.lang.IllegalArgumentException: com.github.xiaofei_dev.vibrator: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3802)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3948)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2402)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8136)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
Caused by: java.lang.IllegalArgumentException: com.github.xiaofei_dev.vibrator: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:401)
	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:484)
	at android.app.PendingIntent.getActivity(PendingIntent.java:470)
	at android.app.PendingIntent.getActivity(PendingIntent.java:434)
	at com.github.xiaofei_dev.vibrator.ui.MainActivity.E0(MainActivity.kt:26)
	at com.github.xiaofei_dev.vibrator.ui.MainActivity.B0(MainActivity.kt:46)
	at com.github.xiaofei_dev.vibrator.ui.MainActivity.onCreate(MainActivity.kt:60)
	at android.app.Activity.performCreate(Activity.java:8522)
	at android.app.Activity.performCreate(Activity.java:8486)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3783)
	... 12 more

**Comment by xiaofeidev** [comment]
已修复
